name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle
        
    - run: chmod +x gradlew
    
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
          .gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-
      
    - name: Build
      run: ./gradlew build --info --stacktrace --scan
      
    - name: Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: build/libs
